db_1:
  db_host: "127.0.0.1"
  db_user: "root"
  db_password: "123456"
  db_database: "test"
  db_charset: "utf8"
  db_port: "3306"

db_2:
  db_host: "127.0.0.1"
  db_user: "root"
  db_password: "123456"
  db_database: "test"
  db_charset: "utf8"
  db_port: "3306"