
BASE:
  # log等级
  log_level: "debug"
  # log文件扩展名
  log_extension: ".log"

  # 环境和域名
  test:
    url: "http://jsonplaceholder.typicode.com/"
#    excel测试用例文件的路径
    excel_case_file: "api.xlsx"
    excel_case_sheet: "Sheet1"